const commands = [
  {
    name: 'copilot',
    args: '',
    desc: 'Launch interactive Copilot CLI session',
    detail: 'Starts the interactive terminal UI for GitHub Copilot in the current working directory.',
    example: 'copilot',
  },
  {
    name: 'copilot login',
    args: '',
    desc: 'Authenticate via OAuth device flow',
    detail: 'Opens the device-flow authentication process and stores credentials for future CLI sessions.',
    example: 'copilot login',
  },
  {
    name: 'copilot login --host',
    args: '<url>',
    desc: 'Authenticate against a custom GitHub host',
    detail: 'Targets GitHub Enterprise Cloud data-residency hosts instead of the default github.com endpoint.',
    example: 'copilot login --host https://example.ghe.com',
  },
  {
    name: 'copilot init',
    args: '',
    desc: 'Initialize repository instructions',
    detail: 'Analyzes your repository and creates or updates .github/copilot-instructions.md.',
    example: 'copilot init',
  },
  {
    name: 'copilot help',
    args: '[topic]',
    desc: 'Show help and command topics',
    detail: 'Displays CLI help. Topics include billing, config, commands, environment, logging, monitoring, permissions, and providers.',
    example: 'copilot help\ncopilot help providers',
  },
  {
    name: 'copilot completion',
    args: '<bash|zsh|fish>',
    desc: 'Generate shell completion script',
    detail: 'Prints completion scripts for your shell so tab-completion can be enabled for commands and options.',
    example: 'copilot completion zsh > "${fpath[1]}/_copilot"',
  },
  {
    name: 'copilot mcp',
    args: '',
    desc: 'Manage MCP server configuration',
    detail: 'Use mcp subcommands to list, inspect, add, or remove MCP servers without launching interactive mode.',
    example: 'copilot mcp list --json\ncopilot mcp get github-mcp-server',
  },
  {
    name: 'copilot mcp list',
    args: '[--json]',
    desc: 'List all configured MCP servers',
    detail: 'Lists all configured MCP servers grouped by source. Use --json for machine-readable output.',
    example: 'copilot mcp list\ncopilot mcp list --json',
  },
  {
    name: 'copilot mcp get',
    args: '<name> [--json]',
    desc: 'Inspect one MCP server',
    detail: 'Shows configuration and available tools for a specific MCP server. Use --json for machine-readable output.',
    example: 'copilot mcp get github-mcp-server\ncopilot mcp get github-mcp-server --json',
  },
  {
    name: 'copilot mcp add',
    args: '<name> [opts]',
    desc: 'Add a user-level MCP server',
    detail: 'Adds a local or remote MCP server to ~/.copilot/mcp-config.json with optional transport, tools, timeout, env, and header settings.',
    example: 'copilot mcp add playwright --url https://example.com/mcp --type http --tools "*"',
  },
  {
    name: 'copilot mcp remove',
    args: '<name>',
    desc: 'Remove a user-level MCP server',
    detail: 'Removes a user-level MCP server from ~/.copilot/mcp-config.json. Workspace servers must be edited in their configuration files directly.',
    example: 'copilot mcp remove playwright',
  },
  {
    name: 'copilot plugin',
    args: '',
    desc: 'Manage plugins and marketplaces',
    detail: 'Opens plugin management from the command line for listing, installing, updating, and removing plugins.',
    example: 'copilot plugin list',
  },
  {
    name: 'copilot plugin list',
    args: '',
    desc: 'List installed plugins',
    detail: 'Displays all currently installed Copilot CLI plugins.',
    example: 'copilot plugin list',
  },
  {
    name: 'copilot plugin install',
    args: '<plugin>',
    desc: 'Install a plugin',
    detail: 'Installs a plugin by name from the configured plugin marketplace.',
    example: 'copilot plugin install my-plugin',
  },
  {
    name: 'copilot plugin update',
    args: '[plugin]',
    desc: 'Update plugins',
    detail: 'Updates a specific plugin or all installed plugins to their latest versions.',
    example: 'copilot plugin update\ncopilot plugin update my-plugin',
  },
  {
    name: 'copilot plugin uninstall',
    args: '<plugin>',
    desc: 'Uninstall a plugin',
    detail: 'Removes an installed plugin by name.',
    example: 'copilot plugin uninstall my-plugin',
  },
  {
    name: 'copilot update',
    args: '',
    desc: 'Download and install latest CLI version',
    detail: 'Fetches and installs the latest GitHub Copilot CLI release.',
    example: 'copilot update',
  },
  {
    name: 'copilot version',
    args: '',
    desc: 'Display version and update status',
    detail: 'Prints current version details and checks whether an update is available.',
    example: 'copilot version',
  },
];

const flags = [
  {
    name: '-p, --prompt',
    args: '<prompt>',
    desc: 'Run programmatically and exit',
    detail: 'Non-interactive one-shot mode for scripts and CI. Runs a prompt and exits after completion.',
    example: 'copilot -p "summarize the latest changes"',
  },
  {
    name: '-i, --interactive',
    args: '<prompt>',
    desc: 'Start interactive mode with initial prompt',
    detail: 'Launches interactive mode and immediately sends the supplied initial prompt.',
    example: 'copilot --interactive "create a migration plan"',
  },
  {
    name: '-r, --resume',
    args: '[session]',
    desc: 'Resume previous session',
    detail: 'Opens the session picker or resumes by explicit ID, ID prefix, or case-insensitive session name.',
    example: 'copilot --resume\ncopilot --resume auth-refactor',
  },
  {
    name: '--continue',
    args: '',
    desc: 'Resume most recent session',
    detail: 'Restores the newest session in the current directory, falling back to the global most recent session.',
    example: 'copilot --continue',
  },
  {
    name: '--model',
    args: '<model|auto>',
    desc: 'Select model for this run',
    detail: 'Sets the model explicitly or uses auto selection. Can also be set via COPILOT_MODEL.',
    example: 'copilot --model gpt-5.3-codex "review this module"',
  },
  {
    name: '--mode',
    args: '<interactive|plan|autopilot>',
    desc: 'Set initial agent mode',
    detail: 'Chooses startup mode directly. Cannot be combined with --plan or --autopilot.',
    example: 'copilot --mode plan',
  },
  {
    name: '--plan',
    args: '',
    desc: 'Shorthand for plan mode',
    detail: 'Equivalent to --mode plan. Cannot be combined with --mode or --autopilot.',
    example: 'copilot --plan "outline rollout steps"',
  },
  {
    name: '--autopilot',
    args: '',
    desc: 'Enable autonomous continuation',
    detail: 'Enables autopilot continuation in prompt mode for multi-step autonomous task flow.',
    example: 'copilot --autopilot',
  },
  {
    name: '--max-autopilot-continues',
    args: '<count>',
    desc: 'Cap autopilot continuation count',
    detail: 'Sets a maximum number of continuation messages when autopilot mode is enabled.',
    example: 'copilot --autopilot --max-autopilot-continues 5',
  },
  {
    name: '--output-format',
    args: '<text|json>',
    desc: 'Set output format',
    detail: 'Controls output shape. JSON mode emits JSONL, one JSON object per line.',
    example: 'copilot -p "list TODOs" --output-format json',
  },
  {
    name: '-s, --silent',
    args: '',
    desc: 'Print only agent response',
    detail: 'Suppresses usage stats and non-response metadata, useful for shell pipelines.',
    example: 'copilot -p "generate changelog" --silent',
  },
  {
    name: '--stream',
    args: '<on|off>',
    desc: 'Toggle streaming output',
    detail: 'When on, responses render progressively. When off, output prints after full completion.',
    example: 'copilot -p "explain architecture" --stream on',
  },
  {
    name: '--name',
    args: '<session-name>',
    desc: 'Assign session name',
    detail: 'Sets a friendly name for a new session so it can be resumed by name later.',
    example: 'copilot --name auth-hardening',
  },
  {
    name: '--agent',
    args: '<agent-id>',
    desc: 'Use a custom agent',
    detail: 'Runs with a specific custom agent definition when available in configured agent directories.',
    example: 'copilot --agent code-review',
  },
  {
    name: '--add-dir',
    args: '<path>',
    desc: 'Add allowed directory for file access',
    detail: 'Adds a directory to the file access allow-list. May be passed multiple times.',
    example: 'copilot --add-dir ../shared-lib --add-dir ../infra',
  },
  {
    name: '--allow-all, --yolo',
    args: '',
    desc: 'Enable all permissions',
    detail: 'Enables all tool, path, and URL permissions. Use only in trusted environments.',
    example: 'copilot --allow-all',
  },
  {
    name: '--allow-tool',
    args: '<pattern>',
    desc: 'Allow specific tool pattern',
    detail: 'Allows specific tools without prompts. Supports patterns like shell(git:*), read, write(src/*.ts), or MCP tool names.',
    example: 'copilot --allow-tool "shell(git:*)"',
  },
  {
    name: '--deny-tool',
    args: '<pattern>',
    desc: 'Deny specific tool pattern',
    detail: 'Explicitly blocks tools or tool patterns. Deny rules take precedence over allow rules.',
    example: 'copilot --allow-tool "shell(git:*)" --deny-tool "shell(git push)"',
  },
  {
    name: '--available-tools',
    args: '<tool,...>',
    desc: 'Restrict available tools',
    detail: 'Limits model-visible tools to the provided set. This controls availability, not permission prompts.',
    example: 'copilot --available-tools "read,grep,glob"',
  },
  {
    name: '--excluded-tools',
    args: '<tool,...>',
    desc: 'Remove tools from availability',
    detail: 'Hides selected tools from the model, even if they would otherwise be available.',
    example: 'copilot --excluded-tools "bash,powershell"',
  },
  {
    name: '--allow-url / --deny-url',
    args: '<url|domain>',
    desc: 'Control URL access permissions',
    detail: 'Grants or denies URL/domain access for web fetch and shell URL operations. Deny takes precedence.',
    example: 'copilot --allow-url github.com --deny-url internal.example.com',
  },
  {
    name: '--additional-mcp-config',
    args: '<json|@file>',
    desc: 'Add session-only MCP servers',
    detail: 'Augments MCP config for the current session only using inline JSON or a file prefixed with @.',
    example: 'copilot --additional-mcp-config @./mcp-extra.json',
  },
  {
    name: '--disable-builtin-mcps',
    args: '',
    desc: 'Disable all built-in MCP servers',
    detail: 'Turns off default built-in MCPs such as github-mcp-server, fetch, playwright, and time.',
    example: 'copilot --disable-builtin-mcps',
  },
  {
    name: '--disable-mcp-server',
    args: '<name>',
    desc: 'Disable one MCP server',
    detail: 'Disables a named MCP server. Can be supplied multiple times.',
    example: 'copilot --disable-mcp-server github-mcp-server',
  },
  {
    name: '--plugin-dir',
    args: '<dir>',
    desc: 'Load local plugin directory',
    detail: 'Loads one or more plugin directories at startup for local plugin workflows.',
    example: 'copilot --plugin-dir ./.copilot/plugins',
  },
  {
    name: '--remote / --no-remote / --connect',
    args: '[session-id]',
    desc: 'Control remote steering sessions',
    detail: 'Enable or disable remote access or connect directly to a remote session/task. --connect conflicts with --resume and --continue.',
    example: 'copilot --remote\ncopilot --connect 9d8e7f6a',
  },
  {
    name: '--experimental / --no-experimental',
    args: '',
    desc: 'Toggle experimental features',
    detail: 'Enables or disables experimental behavior for the current launch.',
    example: 'copilot --experimental',
  },
  {
    name: '--mouse / --no-mouse',
    args: '[on|off]',
    desc: 'Control mouse support in alt-screen mode',
    detail: 'Configures mouse capture in alternate screen mode and persists the setting.',
    example: 'copilot --mouse off',
  },
  {
    name: '--log-level',
    args: '<none|error|warning|info|debug|all|default>',
    desc: 'Set logging verbosity',
    detail: 'Controls log verbosity written by Copilot CLI runtime and diagnostics.',
    example: 'copilot --log-level debug',
  },
  {
    name: '--version / -v',
    args: '',
    desc: 'Show version information',
    detail: 'Prints installed version info and exits.',
    example: 'copilot --version',
  },
  {
    name: '--help / -h',
    args: '',
    desc: 'Display CLI help',
    detail: 'Shows command and option help for Copilot CLI and subcommands.',
    example: 'copilot --help',
  },
];

const slashCommands = [
  {
    name: '/help',
    desc: 'Show interactive command help',
    detail: 'Displays available slash commands and interactive usage guidance.',
    example: '/help',
  },
  {
    name: '/model, /models [model]',
    desc: 'View or switch models',
    detail: 'Lists available models or switches to a specific model mid-session.',
    example: '/model\n/model gpt-5.3-codex',
  },
  {
    name: '/plan [prompt]',
    desc: 'Create an implementation plan first',
    detail: 'Switches into planning-first behavior before execution or coding changes.',
    example: '/plan harden auth middleware',
  },
  {
    name: '/compact [focus]',
    desc: 'Summarize history to save context window',
    detail: 'Compacts the conversation and optionally focuses the summary on a particular subsystem or concern.',
    example: '/compact focus on db migration state',
  },
  {
    name: '/clear, /new, /reset [prompt]',
    desc: 'Start a new conversation',
    detail: 'Clears current conversation state and optionally seeds the new thread with a prompt.',
    example: '/new',
  },
  {
    name: '/resume, /continue [session-id]',
    desc: 'Open session picker or resume by ID',
    detail: 'Switches to another session from the picker or by explicit session identifier.',
    example: '/resume\n/continue a1b2c3d4',
  },
  {
    name: '/rename [name]',
    desc: 'Rename current session',
    detail: 'Assigns or regenerates a name for the active session for easier lookup.',
    example: '/rename oauth-rollout',
  },
  {
    name: '/diff',
    desc: 'Review workspace or branch diff',
    detail: 'Opens diff mode to review pending changes and add comments.',
    example: '/diff',
  },
  {
    name: '/review [prompt]',
    desc: 'Run code review agent',
    detail: 'Invokes the built-in code review workflow for changed files and context-aware analysis.',
    example: '/review focus on error handling and tests',
  },
  {
    name: '/research <topic>',
    desc: 'Run deep research workflow',
    detail: 'Launches deep research using codebase context plus GitHub/web sources.',
    example: '/research compare migration rollback strategies',
  },
  {
    name: '/fleet [prompt]',
    desc: 'Parallelize with subagents',
    detail: 'Splits parts of a task across parallel subagents to accelerate multi-threaded workflows.',
    example: '/fleet audit auth, billing, and notifications modules',
  },
  {
    name: '/agent',
    desc: 'Select from available agents',
    detail: 'Opens available agents, including custom agent definitions when present.',
    example: '/agent',
  },
  {
    name: '/tasks',
    desc: 'Manage running tasks and subagents',
    detail: 'Shows task and subagent execution status and allows task lifecycle management.',
    example: '/tasks',
  },
  {
    name: '/mcp [show|add|edit|delete|disable|enable|auth|reload]',
    desc: 'Manage MCP servers in-session',
    detail: 'Interactive control over MCP server config, auth refresh, enabling/disabling, and reload operations.',
    example: '/mcp show\n/mcp auth github-mcp-server',
  },
  {
    name: '/plugin [marketplace|install|uninstall|update|list]',
    desc: 'Manage plugins in-session',
    detail: 'Handles plugin marketplaces and plugin lifecycle commands directly from the interactive session.',
    example: '/plugin list',
  },
  {
    name: '/skills [list|info|add|remove|reload]',
    desc: 'Manage skills',
    detail: 'Lists and administers loaded skills and supports reload when skill files change.',
    example: '/skills list',
  },
  {
    name: '/extensions [manage|mode], /extension',
    desc: 'Manage CLI extensions',
    detail: 'Opens extension management and extension mode controls.',
    example: '/extensions manage',
  },
  {
    name: '/permissions [show|reset]',
    desc: 'Inspect or clear session approvals',
    detail: 'Shows in-memory permission approvals or resets them for the current session.',
    example: '/permissions show',
  },
  {
    name: '/allow-all [on|off|show], /yolo [on|off|show]',
    desc: 'Toggle elevated permission mode',
    detail: 'Enables or disables broad permission grants for tools, paths, and URLs.',
    example: '/allow-all on',
  },
  {
    name: '/add-dir <path>',
    desc: 'Allow an additional directory',
    detail: 'Adds a directory to the file access allow-list for the active session.',
    example: '/add-dir ../shared-lib',
  },
  {
    name: '/cwd, /cd [path]',
    desc: 'Show or change working directory',
    detail: 'Prints current working directory or changes it to a provided path.',
    example: '/cd ../services/api',
  },
  {
    name: '/init',
    desc: 'Initialize project instructions',
    detail: 'Creates or updates repository instruction files to improve future session quality in this project.',
    example: '/init',
  },
  {
    name: '/context',
    desc: 'Show context token usage',
    detail: 'Displays token utilization and context window visualization for the active conversation.',
    example: '/context',
  },
  {
    name: '/env',
    desc: 'Show loaded environment details',
    detail: 'Shows loaded instructions, MCPs, skills, agents, plugins, and related environment state.',
    example: '/env',
  },
  {
    name: '/statusline, /footer',
    desc: 'Configure status line items',
    detail: 'Controls which indicators and metadata appear in the status/footer area.',
    example: '/statusline',
  },
  {
    name: '/usage',
    desc: 'Display usage metrics',
    detail: 'Shows usage statistics and related metrics for the session/runtime.',
    example: '/usage',
  },
  {
    name: '/update, /upgrade',
    desc: 'Update the CLI',
    detail: 'Triggers an update to the latest available Copilot CLI release.',
    example: '/update',
  },
  {
    name: '/version',
    desc: 'Show version info',
    detail: 'Prints CLI version and update status information.',
    example: '/version',
  },
  {
    name: '/logout',
    desc: 'Log out of Copilot',
    detail: 'Ends authenticated session and removes stored credentials.',
    example: '/logout',
  },
  {
    name: '/exit, /quit',
    desc: 'Exit the CLI',
    detail: 'Gracefully terminates the interactive Copilot session.',
    example: '/quit',
  },
];

// GitHub Copilot brand-inspired palette
const theme = {
  bg: [6, 12, 24],
  bgPanel: [11, 20, 36],
  bgSelected: [9, 105, 218],
  bgTooltip: [9, 17, 31],
  bgHeader: [9, 105, 218],
  fgBase: [223, 234, 249],
  fgDim: [118, 141, 173],
  fgAccent: [88, 166, 255],
  fgAccent2: [123, 201, 255],
  fgSelected: [255, 255, 255],
  fgHeader: [243, 248, 255],
  fgCmd: [130, 196, 255],
  fgFlag: [169, 191, 255],
  fgExample: [156, 228, 255],
  fgTooltipHd: [130, 196, 255],
  fgTooltipBdy: [179, 203, 232],
  fgTooltipEx: [156, 228, 255],
  fgSearch: [255, 221, 107],
  fgBorder: [36, 59, 94],
};

export default {
  id: 'copilot',
  displayName: 'GitHub Copilot CLI',
  bin: 'copilot',
  reference: [
    'https://docs.github.com/en/copilot/reference/copilot-cli-reference/cli-command-reference',
  ],
  commands,
  flags,
  slashCommands,
  theme,
};
